### ISSUE TITLE
Scroll doesnt lock 

### ISSUE THREAD

**Issue by amnag090** [biohzrdmx/jQuery.DateSelect#8]
First of thanks for this I use this plugin and its helped me alot
I did have the following issues thoh

->   The scroll does not lock to the date picker div which mean that when I scroll on the day, month or year sliders the page scrolls down as well. which is very irritatating for the user. thus when the user scrolls to select lets say a date of birth the page scrolls down . Im not sure if this already has been fixed and im just too much of a newb to find out

**Comment by biohzrdmx** [comment]
Hi amnag090!

I've just added a callback mechanism to the plugin so that you can get notified when the control is shown/hidden from view, that way you may implement any custom solution to avoid scrolling the view; in the example implementation (`index.html`) I've overriden these callbacks on the `defaults` object and using jQuery I'm disabling the scrollbars on the `html` and `body` elements. That approach is a bit uggly (the page jumps a bit to the sides) but is just a demo on how you may implement a more clean logic.

Please pull the latest changes or download the `.js` file(s) again.

Regards!
